# Generated by Django 5.1.6 on 2025-03-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section_number',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='base.course'),
        ),
    ]
