# Generated by Django 5.1.6 on 2025-03-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_course_section_number_professor_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.coursenumber'),
        ),
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='section_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.section'),
        ),
    ]
