# Generated by Django 5.1.6 on 2025-03-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_course_number_alter_course_section_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='section_number',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
    ]
