# Generated by Django 5.1.6 on 2025-03-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='section_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
