# Generated by Django 5.1.6 on 2025-03-24 23:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_course_section_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='section_number',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ManyToManyField(blank=True, related_name='professors', to='base.professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
