# Generated by Django 5.1.6 on 2025-03-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_course_section_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_dept', 'course_number']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='dept',
            new_name='course_dept',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='number',
            new_name='course_number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='professor',
            new_name='course_professors',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='students',
            new_name='course_students',
        ),
    ]
