# Generated by Django 5.1.6 on 2025-03-27 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_course_options_rename_dept_course_course_dept_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['department', 'number', 'section_number']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_dept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_students',
            new_name='students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_professors',
        ),
        migrations.AddField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors', to='base.professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='section_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
