# Generated by Django 5.1.7 on 2025-03-26 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_professor_rating_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review',
        ),
    ]
