# Generated by Django 5.1.6 on 2025-03-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='rating',
        ),
    ]
