# Generated by Django 5.1.7 on 2025-03-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_professor_rating_review'),
        ('base', '0017_alter_course_options_and_more'),
    ]

    operations = [
    ]
