# Generated by Django 5.1.7 on 2025-03-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_merge_20250327_2027'),
        ('base', '0018_remove_professor_rating'),
    ]

    operations = [
    ]
