# Generated by Django 5.1.7 on 2025-04-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_remove_professor_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassScedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_time", models.CharField(max_length=100)),
                (
                    "meeting_days",
                    models.ManyToManyField(
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                            ("SUN", "Sunday"),
                        ],
                        max_length=7,
                        to="base.course",
                    ),
                ),
            ],
        ),
    ]
