# Generated by Django 5.1.7 on 2025-04-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_classscedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="classscedule",
            name="courses",
            field=models.ManyToManyField(to="base.course"),
        ),
        migrations.RemoveField(
            model_name="classscedule",
            name="meeting_days",
        ),
        migrations.AddField(
            model_name="classscedule",
            name="meeting_days",
            field=models.CharField(
                choices=[
                    ("MON", "Monday"),
                    ("TUE", "Tuesday"),
                    ("WED", "Wednesday"),
                    ("THU", "Thursday"),
                    ("FRI", "Friday"),
                    ("SAT", "Saturday"),
                    ("SUN", "Sunday"),
                ],
                default="Not Specified",
                max_length=7,
            ),
        ),
    ]
