# Generated by Django 5.1.6 on 2025-04-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
