# Generated by Django 5.1.6 on 2025-04-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
