# Generated by Django 5.1.7 on 2025-04-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_classscedule_courses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classscedule",
            name="room_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
