# Generated by Django 5.1.5 on 2025-04-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_review_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
