# Generated by Django 5.1.6 on 2025-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_professor_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['department', 'number']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='section_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ManyToManyField(null=True, related_name='professor', to='base.professor'),
        ),
    ]
