# Generated by Django 5.1.6 on 2025-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_course_options_remove_course_section_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ManyToManyField(related_name='professor', to='base.professor'),
        ),
    ]
