# Generated by Django 5.1.6 on 2025-04-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_course_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
