# Generated by Django 5.1.6 on 2025-04-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_review_flagged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='username',
            new_name='user_account',
        ),
    ]
