# Generated by Django 5.1.5 on 2025-04-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_review_flagged_tutor_course_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='username',
            new_name='user_account',
        ),
    ]
