# Generated by Django 5.1.6 on 2025-04-25 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_rename_username_professor_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section_number',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor', to='base.professor'),
        ),
    ]
