# Generated by Django 5.1.5 on 2025-04-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_course_section_number_remove_course_professor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pending_tutor',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='base.tutor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ManyToManyField(blank=True, null=True, related_name='course', to='base.tutor'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'number', 'section_number')},
        ),
    ]
