# Generated by Django 5.1.6 on 2025-04-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_review_reply'),
        ('base', '0032_course_pending_tutor_alter_course_tutor_and_more'),
    ]

    operations = [
    ]
