# Generated by Django 5.1.6 on 2025-04-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_merge_20250428_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='available',
            field=models.TextField(default=False),
        ),
    ]
