# Generated by Django 5.1.6 on 2025-04-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_tutor_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pending_tutor',
            field=models.ManyToManyField(blank=True, related_name='courses', to='base.tutor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ManyToManyField(blank=True, related_name='course', to='base.tutor'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='available',
            field=models.TextField(default=False, null=True),
        ),
    ]
